import os
import sys
import shutil

# Add src to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../src")))

from aeroloop.agents.geometry_design_agent import GeometryDesignAgent
from aeroloop.schemas.geometry import GeometryDesignRequest, GeometryValidationOptions

VEHICLE_TYPES = [
    "evtol",
    "vtol",
    "rotorcraft",
    "fixed_wing",
    "lift_cruise",
    "lift_cruise_vtol",
    "tiltrotor",
    "small_helicopter",
    "small_aircraft"
]

def test_all_geometry_types():
    agent = GeometryDesignAgent()
    failed_types = []
    
    print("Starting integration test for all VehicleTypes supported by the OpenVSP GeometryDesignAgent...\n")
    
    for ac_type in VEHICLE_TYPES:
        print(f"--- Testing Geometry Generation for '{ac_type}' ---")
        
        out_dir = f"./test_geometry_out_{ac_type}"
        
        req = GeometryDesignRequest(
            geometry_request_id=f"test_{ac_type}",
            run_id="test_run",
            mission_id="test_mission",
            candidate_id=f"cand_{ac_type}",
            configuration_id="config_1",
            vehicle_type=ac_type,
            geometry_template="maximal",
            design_parameters={
                "fuselage_length_m": 5.0,
                "fuselage_diameter_m": 1.5,
                "wing_area_m2": 10.0,
                "wingspan_m": 10.0,
                "root_chord_m": 1.2,
                "tip_chord_m": 0.8,
                "aspect_ratio": 10.0,
                "rotor_count": 4 if "rotor" in ac_type else 1,
                "rotor_radius_m": 1.0,
                "total_disk_area_m2": 25.0
            },
            output_directory=out_dir,
            validation_options=GeometryValidationOptions(validate_mesh=False)
        )
        
        result = agent.process_request(req)
        
        if result.status in ["success", "success_with_warnings"]:
            print(f"✅ Success for '{ac_type}'!")
            print(f"   Artifact saved at: {result.geometry_artifacts.vsp3_file_path}\n")
        else:
            print(f"❌ Failed for '{ac_type}'!")
            for err in result.errors:
                print(f"   Error: {err.message}\n")
            failed_types.append(ac_type)
            
        # Cleanup temporary test directory
        if os.path.exists(out_dir):
            shutil.rmtree(out_dir)
            
    if failed_types:
        print(f"❌ Overall Test Failed. The following types failed: {', '.join(failed_types)}")
        sys.exit(1)
    else:
        print("✅ All VehicleTypes were successfully generated by OpenVSP!")
        sys.exit(0)

if __name__ == "__main__":
    test_all_geometry_types()
